version: '3.8'

services:
  rss-aggregator:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: rss-advanced-aggregator
    ports:
      - "8080:8080"
    restart: unless-stopped
    
    # Environment variables for enhanced features
    environment:
      - TZ=Asia/Kolkata
      - GO_ENV=production
      - RSS_REFRESH_INTERVAL=5m
      - MAX_ARTICLES_CACHE=1000
      - WEBSOCKET_TIMEOUT=60s
      
    # Resource limits for 4GB machine (conservative)
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
    
    # Enhanced health check testing multiple endpoints
    healthcheck:
      test: |
        wget --no-verbose --tries=1 --spider http://localhost:8080/api/status &&
        wget --no-verbose --tries=1 --spider http://localhost:8080/api/analytics &&
        wget --no-verbose --tries=1 --spider http://localhost:8080/api/sentiment
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 10s
      
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"
        
    # Labels for better container management
    labels:
      - "app=rss-aggregator"
      - "version=enhanced"
      - "description=Advanced RSS News Aggregator with Analytics"
      - "maintainer=your-team"
      
    # Network configuration for WebSocket support
    networks:
      - rss-network
      
    # Volume for potential future use (logs, cache, etc.)
    volumes:
      - rss-logs:/app/logs
      
# Networks
networks:
  rss-network:
    driver: bridge
    
# Volumes  
volumes:
  rss-logs:
    driver: local
